language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - pytest testSuite.py
  - cd tests
  - lettuce
  #- git clone https://github.com/alexisfranche/we-re-board-backend.git
  #- python setup.py install
