language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"

matrix:
  allow_failures:
    - python: "2.6"
    - python: "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install gunicorn==20.0.4
# command to run tests
script:
  - pytest testSuite.py
  - cd tests
  - lettuce