##This template is for a django project with a postgresql database
##It will change if we choose a different langauge and so on
# version: 2.1
# jobs:
#   build:
#     working_directory: ~/charego-backend
#     docker:
#       - image: circleci/python:3.6.4
#         environment:
#           PIPENV_VENV_IN_PROJECT: true
#           DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
#       - image: circleci/postgres:9.6.2
#         environment:
#           POSTGRES_USER: CharegoDevUser
#           POSTGRES_DB: CharegoDB
#     steps:
#       - checkout
#       - run: sudo chown -R circleci:circleci /usr/local/bin
#       - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
#       - restore_cache:
#           key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
#       - run:
#           command: |
#             sudo pip3 install pipenv
#             pipenv install
#             pipenv install django
#             pipenv install psycopg2
#             pipenv install pillow 
#       - save_cache:
#           key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
#           paths:
#             - '.venv'
#             - '/usr/local/bin'
#             - '/usr/local/lib/python3.6/site-packages'
#       - run:
#           command: |
#             pipenv run python manage.py test
#       - store_test_results:
#           path: test-results
#       - store_artifacts:
#           path: test-results
#           destination: tr1